themes/citylights.conf

Almost finished, probably not update anymore.

fix : add os_titlebar color and mark color

---

themes/nightfly.conf

Sync to latest https://github.com/bluz71/vim-nightfly-guicolors/blob/master/terminal_themes/kitty-theme.conf

Update nightfly.conf to latest

---

themes/modus-operandi.conf
themes/modus-vivendi.conf

Hello,
If that is possible, I would like to add modus-themes made by Protesilaos Stavrou with Emacs in mind. If there is anything that I would need to modify or fix, please let me know.
Thank you!

Add modus-operandi and modus-vivendi themes

---

themes.json
themes/rose-pine-dawn.conf
themes/rose-pine-moon.conf
themes/rose-pine.conf

Includes the three variants of [Rosé Pine](https://github.com/rose-pine/kitty).

Add Rosé Pine themes

---

themes/catppuccin.conf

Added catppuccin.conf theme file based on https://github.com/catppuccin/kitty

Add catppuccin theme

---

themes/Kaolin_Aurora.conf
themes/Kaolin_Dark.conf
themes/Kaolin_Light.conf

Hello,
I would like to add Kaolin themes made by Ogden Webb originally for Emacs. If there is anything that I would need to modify or fix, please let me know.
Thank you!

Add Kaolin themes

---

themes/Kaolin_Galaxy.conf

Hello,
I would like to add last Kaolin theme which is based on Sebastian Andaur arts.
Thank you!

Add Kaolin Galaxy theme

---

themes/Kaolin_Breeze.conf
themes/Kaolin_Ocean.conf
themes/Kaolin_Temple.conf

Hello,
I would like to add three other Kaolin themes, one light with warmer tones, one earthy dark theme (similar to Zenburn, but a bit more readable and less green) and dark blue ocean theme.
Thanks!

Add other Kaolin themes

---

themes/modus-operandi.conf
themes/modus-vivendi.conf

Hello,
I would like to add missing borders and tabs colors to modus themes. Thanks!

Configure borders and tabs colors for modus themes

---

themes/AtomOneLight.conf

Fix wrong selection colors AtomOneLight

---

themes/HachikoRed.conf

HachikoRed.conf added

---

themes/modus-operandi.conf
themes/modus-vivendi.conf

Hello,
I would like to update current Modus themes with better, more consistent with the theme tab bar colors.
Thanks!

Update Modus themes colors

---

themes/Doom_One.conf
themes/Doom_One_Light.conf
themes/Doom_Vibrant.conf

Hello,
I would like to add three themes inspired by Atom One ported from Doom Emacs flagship themes.
Thanks!

Add Doom One themes

---

themes/Zesty_Dawn.conf

I don't know what's wrong with the spacing. It looks fine in the editor.

Added Zesty Dawn

---

themes/breath2.conf

Added Breath2

---

themes/fairyfloss.conf

Adding the popular **fairyfloss** theme, inspired by https://sailorhg.github.io/fairyfloss/.

Create fairyfloss theme!

---

themes/dark_pride.conf

Add a trans-pride colour inspired theme

Add a dark trans-pride colour inspired theme

---

themes/rose-pine-dawn.conf
themes/rose-pine-moon.conf
themes/rose-pine.conf

Includes updated upstream url and improved cursor contrast

Update Rosé Pine themes to match upstream

---

themes/DarkOneNuanced.conf

Add DarkOneNuanced theme imported from KDE store.

Add DarkOneNuanced theme

---

themes/moonlight.conf

Add [moonlight theme](https://github.com/ramonsaraiva/kitty-moonlight) - A port of moonlight vscode extension for kitty terminal

Add moonlight theme

---

themes/everforest_dark_hard.conf
themes/everforest_dark_medium.conf
themes/everforest_dark_soft.conf
themes/everforest_light_hard.conf
themes/everforest_light_medium.conf
themes/everforest_light_soft.conf

Variations based on the Vim theme Everforest made by [sainnhe](https://github.com/sainnhe/everforest)
Soft | Medium | Hard

Everforest themes

---

themes/Alabaster.conf
themes/Alabaster_Dark.conf

Adapted light and dark versions of the Alabaster color scheme for ST by Nikita Prokopov. Submitting for review and inclusion in the collection.

Add Alabaster color themes

---

themes/cyberpunk.conf

Cyberpunk colorscheme for kitty based on the Cyberpunk VIM Colorscheme by thedenisnikulin.

Added the cyberpunk theme

---

themes/purpurite.conf

This PR Adds [purpurple](https://github.com/purpurite)'s kitty theme to this repository.
The only files added are `purpurite.conf` in the `themes` folder.
Thanks and Good Day/Night

Add purpurite theme

---

themes/leaf_dark.conf
themes/leaf_light.conf

https://github.com/qewer33/leaf-kde

added leaf themes

---

themes/VSCode_Dark.conf

Hi there, I ported the VS Code default dark theme that makes Kitty look like its integrated terminal

Add vscode dark default theme

---

themes/shadotheme.conf

Added [shadorain's beautiful theme, shadotheme](https://github.com/Shadorain/shadotheme) to the branch, the config file is tested, and looks good :3

Addition of shadotheme by shadorain

---

themes/Monoindustrial.conf

Color theme for kitty based on the Monoindustrial theme from the TextMate editor.

Add Monoindustrial theme

---

themes/midsummer-night.conf

Just a personal theme that I've been using over the years ^^

Add Midsummer Night Theme

---

themes/noirblaze.conf

I apologize, I've previously submitted a PR (#84), that was slightly out of date. This PR fixes the "issues" (namely a better green color).

Fix noirblaze theme

---

themes/cherry-midnight.conf
themes/cherry.conf

Hello
I would like to add cherry themes for kitty to compliment [cherry-kde](https://github.com/nullxception/cherry-kde) theme, thanks

Add Cherry themes

---

themes/Srcery.conf

This PR updates the Srcery theme to follow the template file by adding metadata and using the same headers and capitalization.

Update srcery to follow template.conf

---

themes/Neowave.conf

A very neon theme that I've been using for a while.

Add Neowave theme.

---

themes/Box.conf

Primary color style: https://www.hackthebox.com/docs/Hack_The_Box_Brand_Assets_Guide.pdf

Added Box.conf Theme

---

themes.json
themes/flexoki_dark.conf
themes/flexoki_light.conf

Add both light and dark variants of the [Flexoki](https://github.com/kepano/flexoki) theme.

Add Flexoki Themes

---

themes/everforest_dark_hard.conf
themes/everforest_dark_medium.conf
themes/everforest_dark_soft.conf

black:
selection:
black:
selection:

Update Everforest palette

---

themes/Adapta_Nokto_Maia.conf

This theme is the default for manjaro community edition i3.

add adapta nokto maia

---

themes/Cyberpunk-Neon.conf

Adding Cyberpunk Neon theme from https://github.com/Roboron3042/Cyberpunk-Neon

Cyberpunk Neon theme

---

themes.json
themes/Eldritch.conf

Adds Eldritch theme https://github.com/eldritch-theme/kitty

Eldritch theme

---

themes/Eldritch.conf

A few updates for my color theme, I assume this repo doesnt auto pull changes from upstream

Eldritch theme updates

---

themes/kanagawa.conf
themes/kanagawa_dragon.conf
themes/kanagawa_light.conf

Themes taken from [kanagawa.nvim](https://github.com/rebelot/kanagawa.nvim), thanks to @rebelot. I have done some formatting to respect the template as much as possible.

add kanagawa themes

---

themes/Gnome-ish_gray-on-black.conf

That's a theme based on the colors of the classic Gnome Terminal.

Add "Gnome-ish gray-on-dark" theme

---

themes/selenized-black.conf
themes/selenized-dark.conf
themes/selenized-light.conf
themes/selenized-white.conf

Request to add the [selenized theme](https://github.com/jan-warchol/selenized/) to kitty's themes.
The selenized repository already contained the required .conf files, but they were not available through kitty-themes yet.

Add Selenized themes

---

themes/spaceduck.conf

This adds a new theme to the repo called Spaceduck for kitty terminal.
[Spaceduck](https://github.com/pineapplegiant/spaceduck-terminal) theme is developed by [pineapplegiant](https://github.com/pineapplegiant) for terminals and text editors such as Vim. Author describes the theme's inspiration as a desire to feel like you're in space.

Add spaceduck theme

---

themes/bl1nk.conf

---
name: Add a new theme
about: Use the following template if you want a new theme to be included in the collection.
title: Add bl1nk to the collection.
labels: theme request
assignees: kovidgoyal
---
Please, include **[bl1nk](https://github.com/dhay3/kitty-bl1nk)** in the collection.
Below is a screenshot of the theme in kitty.

Add bl1nk theme

---

themes.json
themes/tender.conf

- Also ran the gen-metadata.py to generate the tender entry, saving you some time?!
- link to [tender-kitty theme ](https://github.com/CompEng0001/tender-kitty)
- has been included by tender-vim [63#partial-pull-merging](https://github.com/jacoborus/tender.vim/pull/63#partial-pull-merging)

Add Tender theme collection

---

themes/phanes.conf

Added my own color scheme called Phanes (https://github.com/wolgamot/phanes_colors)

Added Phanes theme

---

themes/pink_lavender.conf

add my own pink lavender theme as defined [here ](https://github.com/playerofceleste/pink-lavender)

add pink lavender theme

---

themes/vague.conf

Vague theme inspired in vague.nvim

Add vague theme

---

minimal-kiwi-theme.conf

Theme is inspired by [VSCode "Minimal Kiwi" theme](https://marketplace.visualstudio.com/items?itemName=PranjalKumar.minimal-kiwi)

Add "Minimal Kiwi" theme

---

themes/ANSI-87.conf

Basic theme based on the VGA ANSI colors on old IBM computers.
Cursor-, text- & selection-color theming based on the DOS shell.

Add IBM 16C VGA

---

themes/daintyDark.conf

Added Dainty Dark theme

---

themes/Modus_Operandi.conf
themes/Modus_Operandi_Tinted.conf
themes/Modus_Vivendi.conf
themes/Modus_Vivendi_Tinted.conf

Hello!
This PR updates some colors to be more true to the upstream. Cursor colors for tinted variants were also updated (as they are in color in the original theme).

Sync Modus themes with upstream

---

themes/graphite.conf

Changes made:
* Added a new `graphite` theme

Add `graphite` theme.

---

themes/mellow.conf

Hi!
I'd like to add mellow theme here. Original repo: https://github.com/mellow-theme/mellow.nvim

Add mellow theme

---

themes/Ayaka.conf

added ayaka theme (its very cute)

---

themes/bliss.conf

Adds the Bliss theme to kitty, based on https://github.com/joshjon/bliss-iterm

Add bliss theme to kitty

---

themes/E-Ink-Dark.conf
themes/E-Ink.conf

Add E-Ink theme 
https://github.com/alexxGmZ/e-ink.kitty

Add E-Ink theme

---

themes/E-Ink-Dark.conf
themes/E-Ink.conf

fix: grascale -> grayscale

---

themes/Wood.conf

Hi, I would like to add the wood theme.
This is copied from [commit 6af728b44 of wood-theme](https://github.com/ed9w2in6/wood-theme/blob/51d0b5cf67522fe95c408fd2400afe8a42fda025/kitty/Wood.conf).
Thank you for your time again.

Add wood theme
