kovidgoyal/kitty-themes

themes/Campbell.conf
Campbell is the default theme of Windows Terminal and cmd. I'm not really sure how ownership works when it comes to themes like this (such as whether the author should be Microsoft or me, who only ported it), so I've left those fields out. Just tell me if something needs to be fixed and I'll take care of it.
For reference:
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes
https://devblogs.microsoft.com/commandline/updating-the-windows-console-colors/
=> new theme: Campbell

themes.json, themes/wizzy-bright.conf, themes/wizzy-muted.conf
Submission of a new theme set named Wizzy. There are two variants, where the difference is in brightness of text, hence the naming. However, they are both dark themes.
Inspiration for this came from Wryan, for which they are both heavily based on the primary colors of.
I have updated the repo themes metadata, and conformed the theme files to the template.
=> 'wizzy' theme submission

template.conf
The visual bell color will be configurable in a future release of kitty.
This can now be tried in the nightly version.
=> Add a new color option: visual_bell_color

template.conf
Adds the new `tab_bar_margin_color` option to the template.
Use `#:` starters for document lines and adjust the blank line spacing.
=> Add option tab_bar_margin_color

themes.json, themes/Solarized_Dark.conf, themes/Solarized_Light.conf
Hello! 
This is a small rework, since I noticed that currently Solarized Light version available in kitty-themes repository is not true to the original. I have also updated it with information about license and author.
As could be inspected in provided link, Solarized [explicitly defines][1] background and foreground colors:
* #fdf6e3 (base 3) for background
* #657b83 (base 00) for primary content
* #93a1a1 (base 1) for comments/secondary content
* #eee8d5 (base 2) for background highlights
* #586e75 (base 01) for emphasized content
[1]: https://ethanschoonover.com/solarized/#usage-development
Best regards,
alternateved
=> Use true Solarized Light colors

themes/OneHalf.conf
In sonph/onehalf#92 (upstream theme), "bright black" was set to a different shade of gray from "black".
=> onehalf: Update color8 to match upstream

themes.json, themes/PaperColor_dark.conf, themes/PaperColor_light.conf, themes/moonlight.conf
It looks like the license format I used in my previous PR was wrong.
This PR fixes the few occurrences that include markdown in their "license" attribute.
=> Remove markdown formatting from licenses

themes.json, themes/GruvboxMaterialDarkHard.conf, themes/GruvboxMaterialDarkMedium.conf, themes/GruvboxMaterialDarkSoft.conf, themes/GruvboxMaterialLightHard.conf, themes/GruvboxMaterialLightMedium.conf, themes/GruvboxMaterialLightSoft.conf
- Add metadata (author, license, blurb, upstream), update `themes.json`
- Sync colors with [upstream](https://github.com/rsaihe/gruvbox-material-kitty/tree/d79d7c1f98078101cc4df9c759683c64ce749faa/colors) (the latest changes were contributed by the author of the color scheme)
- Remove tab and font attributes (I believe this kind of customizations should be at the discretion of the user, but I'm fine reverting them too)
=> Update Gruvbox Material themes

themes.json, themes/everforest_dark_hard.conf, themes/everforest_dark_medium.conf, themes/everforest_dark_soft.conf, themes/everforest_light_hard.conf, themes/everforest_light_medium.conf, themes/everforest_light_soft.conf
The base 16 colors of the current Everforest scheme(s) follow the [upsteam Everforest palette](https://github.com/sainnhe/everforest) rather loosely; dark theme variants "borrow" colors from the light palette, and vice-versa. This is not the case in the original palette, which defines its [background](https://github.com/sainnhe/everforest/blob/3883583eb32776203e52afaa421b1a590b689ede/autoload/everforest.vim#L62-L91) and [foreground](https://github.com/sainnhe/everforest/blob/3883583eb32776203e52afaa421b1a590b689ede/autoload/everforest.vim#L123-L159) colors strictly.
The full rationale, as well as before/after screenshots, can be found at ewal/kitty-everforest#3.
=> Use strict upstream palettes in Everforest themes

themes/GitHub_Dark.conf, themes/GitHub_Dark_Colorblind.conf, themes/GitHub_Dark_Dimmed.conf, themes/GitHub_Dark_High_Contrast.conf, themes/GitHub_Light.conf, themes/GitHub_Light_Colorblind.conf, themes/GitHub_Light_High_Contrast.conf
Add several themes that uses the official GitHub palette, based on https://github.com/primer/github-vscode-theme.
The files are generated via https://github.com/kidonng/cherry/blob/master/deno/kitty-github-theme.ts.
=> Add GitHub themes

themes/everforest_dark_hard.conf, themes/everforest_dark_medium.conf, themes/everforest_dark_soft.conf, themes/everforest_light_hard.conf, themes/everforest_light_medium.conf, themes/everforest_light_soft.conf
Port of the [recent changes](https://github.com/sainnhe/everforest/compare/d855af543410c4047fc03798f5d58ddd07abcf2d..81041b40335344fba9aa8f100bdfc4b3dffc564d) to the Everforest palette.
Those were mainly an effort to improve the contrasts, so only background colors are affected.
---
Example of what to expect:
<details>
<summary>:framed_picture: Screenshots</summary>
</details>
=> Update Everforest palette

themes/Kaolin_Breeze.conf, themes/Kaolin_Light.conf, themes/Modus_Operandi.conf, themes/Modus_Operandi_Tinted.conf
Proper fix for https://github.com/kovidgoyal/kitty-themes/issues/68 and https://github.com/kovidgoyal/kitty/issues/6320 where `color15` wasn't visible for `select_tab` and `unicode_input` kittens. This shouldn't break TUI applications as https://github.com/kovidgoyal/kitty-themes/pull/85 did.
=> Fix Modus and Kaolin themes visibility for kittens

themes/adwaita_dark.conf, themes/adwaita_darker.conf, themes/adwaita_light.conf
Based on the neovim theme, https://github.com/Mofiqul/adwaita.nvim
=> Adwaita themes

themes/Constant_Perceptual_Luminosity_dark.conf
Optimized for color differences subject to constant luminosity.
blurb: 
ANSI term colors picked with OKHSL maximizing difference
in color subject to constant perceptual luminosity so that all
colors are readable on dark screens even against transparency
yet gentle on the eyes in dark environments.
for colors (starting with red at 30 degrees) luminosity is .4, .6 (bright)
.5 for white(gray), .7 bright white (light gray)
0 for black and .3 for bright black
For transparency I find these work ok:
```
background_opacity 0.7
dynamic_background_opacity yes
```
=> add Constant Perceptual Luminosity (dark) theme,

themes/Nord.conf
Synchronize with the official style guidelines outlined in
https://www.nordtheme.com/docs/colors-and-palettes.
Notable changes are:
* cursor: Use nord4 as prescribed in the style guidelines.
* color11: Use nord12 to utilize all colors in the Aurora palette.
* color12: Use nord10 to utilize all colors in the Frost palette.
Window, Tab, and Marker colors are provided in adherence to the style
guidelines where reasonably applicable.
---
I created two commits to aid in reviewing this PR. The first commit normalizes the color values to lowercase, and the second introduces the actual changes. There is some churn to align the file with `template.conf`. If the rearranging of sections is undesirable, please let me know and I rework the PR to make the diff more amenable for review.
=> Nord: Synchronize with upstream style guidelines

themes/OneDark-Pro.conf
Add [my One Dark Pro Theme](https://github.com/VictorPLopes/OneDark-Pro-Kitty-Terminal), inspired by Binaryify's One Dark Pro theme for Visual Studio Code.
=> Add One Dark Pro Theme

themes/spaceduck.conf
Unnecessary URLs have been removed from the theme and author metadata fields. This helps prevent theme name from displaying with the URL in the themes list when using the command `kitty +kitten themes`.
=> Remove URLs from theme name and author for spaceduck

themes/base2tone-cave-dark.conf, themes/base2tone-desert-dark.conf, themes/base2tone-drawbridge-dark.conf, themes/base2tone-earth-dark.conf, themes/base2tone-evening-dark.conf, themes/base2tone-field-dark.conf, themes/base2tone-forest-dark.conf, themes/base2tone-garden-dark.conf, themes/base2tone-heath-dark.conf, themes/base2tone-lake-dark.conf, themes/base2tone-lavender-dark.conf, themes/base2tone-mall-dark.conf, themes/base2tone-meadow-dark.conf, themes/base2tone-morning-dark.conf, themes/base2tone-motel-dark.conf, themes/base2tone-pool-dark.conf, themes/base2tone-porch-dark.conf, themes/base2tone-sea-dark.conf, themes/base2tone-space-dark.conf, themes/base2tone-suburb-dark.conf
These are dark versions of [Base2Tone](https://base2t.one) for kitty. I created a dedicated repo of [Base2Tone for kitty](https://github.com/atelierbram/Base2Tone-kitty), so people can seek out the light themes over there if they want to do so.
=> added (duotone) Base2Tone dark themes

themes/base4tone-classic-d-dark.conf, themes/base4tone-classic-i-dark.conf, themes/base4tone-classic-p-dark.conf, themes/base4tone-classic-s-dark.conf, themes/base4tone-classic-w-dark.conf, themes/base4tone-modern-n-dark.conf, themes/base4tone-modern-w-dark.conf
These are 7 dark versions of some of the [Base4Tone](https://atelierbram.github.io/syntax-highlighting/base4tone/) themes for kitty. I created a dedicated repo of [Base4Tone for kitty](https://github.com/atelierbram/Base4Tone-kitty), so people can seek out the other dark themes and the light themes over there as well if they want to do so.
=> added 7 Base4Tone dark themes

themes.json, themes/Carbonfox.conf, themes/Dawnfox.conf, themes/Dayfox.conf, themes/Duskfox.conf, themes/Nordfox.conf, themes/Terafox.conf
Currently only `Nightfox.conf` is available. This PR adds other themes (foxes) from the neovim colorscheme [nightfox.nvim](https://github.com/EdenEast/nightfox.nvim).
I have also run the `gen-metadata.py` script to update `themes.json`.
=> Add other themes in the nightfox.nvim theme collection.

themes/blueberry-mango.conf
I have added a theme file for Blueberry Mango, a pastel dark theme that I designed to help with my mixed red-green and blue-yellow colorblindness. It is loosely based on the [Blueberry Banana theme from remmina](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/remmina/Banana%20Blueberry.colors), but has been modified to provide better contrast between color pairs and the background.
An [upstream repo](https://github.com/janbridley/blueberry-mango) has also been created to house the theme, with an example image and a few README examples.
=> Add blueberry-mango theme
